name: make

on:
  push:
    tags:
      - 'kube-proxy*'
  
jobs:
  push_to_registry: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 #all history for all branches and tags

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: clay2019/kube-proxy

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./kube-proxy
          push: true
          tags: 0 #auto-make
          labels: ${{ steps.meta.outputs.labels }}